### ISSUE TITLE
[1.20.1] apotheosis gems can't be socketed using smithing table and this mod gem's are disabled

### ISSUE THREAD

**Issue by Manaether** [Daripher/Passive-Skill-Tree#100]
Mods : 
Apotheosis-1.20.1-7.1.0.jar
ApothicAttributes-1.20.1-1.2.1.jar
PassiveSkillTree-1.20.1-BETA-0.6.2c-all.jar

**Comment by luckyleviboy** [comment]
Did you ever get this fixed??? I'm new to modding and stuff so i'm having trouble trying to figure this out
