### ISSUE TITLE
Crash with null result from AbstractArrow#getPickupItem() from other mods

### ISSUE THREAD

**Issue by Owls-Parliament** [Daripher/Passive-Skill-Tree#101]
While using the Rainfall Serenity bow provided by Celestisynth (https://www.curseforge.com/minecraft/mc-mods/celestisynth), the game crashed. Not Enough Crashes (https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge) identified Passive Skill Tree to be the culprit (after I eliminated the other mods to which it pointed), though it is possible that it is on the end of Celestisynth. Either way, the bow only crashed when an entity was hit, but not if it hit a block. As soon as any entity was hit, the game immediately crashed.
I will be sending a copy of this crash to the creator of Celestisynth as well. (https://github.com/AquexTheSeal/Celestisynth/issues/33)
After removing Passive Skill Tree, the bow item from Celestisynth worked correctly.
[crash-2023-12-14_21.40.23-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13680698/crash-2023-12-14_21.40.23-client.txt)

**Comment by 5stigma** [comment]
The version PassiveSkillTree-1.19.2-BETA-0.5.10b is Ok
