### ISSUE TITLE
experience is now per HOUR?

### ISSUE THREAD

**Issue by Aceplante** [Daripher/Passive-Skill-Tree#113]
1.5 experience per HOUR is literally completely useless. It used to be per minute, It was fine as is. Why did you change it?

Either massively buff the amount of experience or make it much shorter again, how about a minute?

**Comment by Daripher** [comment]
Make sure you are using the latest version, I changed that attribute to exp per minute ages ago.

**Comment by Aceplante** [comment]
ah apologies I was on a server that must not have updated
