### ISSUE TITLE
Crash with From The Shadow Mod

### ISSUE THREAD

**Issue by 5stigma** [Daripher/Passive-Skill-Tree#116]
Cleric attack crash
[crash-2023-12-18_03.05.42-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13708031/crash-2023-12-18_03.05.42-server.txt)

**Comment by Daripher** [comment]
Report that to the From The Shadow mod's author and tell them that they shouldn't return `null` in the `AbstractArrow#getPickupItem()`.
I will also add a null check in my mod to prevent such errors in the future.

**Comment by Daripher** [comment]
Duplicate of #101

**Comment by 5stigma** [comment]
The version PassiveSkillTree-1.19.2-BETA-0.5.10b is Ok
