### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by EyeSeeIce** [Daripher/Passive-Skill-Tree#119]
The game crashes when running the editor

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke 
"String.isEmpty()" because "p_92383_" is null
```

**Comment by Daripher** [comment]
Can you provide a full crash log?

**Comment by EyeSeeIce** [comment]
ofc
[crash-2023-12-19_22.07.09-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13719441/crash-2023-12-19_22.07.09-client.txt)

**Comment by Daripher** [comment]
Let me know if this issue is fixed by the latest update, because I couldn't reproduce it myself
