### ISSUE TITLE
Boot crash with new version

### ISSUE THREAD

**Issue by SeanChengN** [Daripher/Passive-Skill-Tree#124]
Crash version: 0.6.3, 0.6.3a
Normal version: 0.6.2e and older
Other mods have not changed.
[crash-2023-12-21_10.12.47-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/13734377/crash-2023-12-21_10.12.47-client.txt)

**Comment by Daripher** [comment]
Doesn't seem to be related to PST?

**Comment by SeanChengN** [comment]
> Doesn't seem to be related to PST?

My bad, the new version uses Item Production Lib, I did not check the change log carefully.
