### ISSUE TITLE
Crafted food damage bonus give infinite damage (BUG)

### ISSUE THREAD

**Issue by nik122317** [Daripher/Passive-Skill-Tree#128]
I a player under the effects of even a single perk of crafted food damage bonus hits an entity a few times, then the player will get nigh infinite damage until the effect wears off. 
One of bugs sprouting from this bug is that some mobs who got hit will get their hp set to NaN, instead of getting killed.

(+ one minor bug (?) , even though the perks give buffs in percentage forms, the icon shown in the inventory will show it multiplication. For example if you presumably have 8 percent buff to dmg, the icon and effect will show it as VIII)

By the way, the version of the mod I'm using is 0.6.2e, since the later versions require Item Production Lib, which gives me a fatal error.

**Comment by Daripher** [comment]
I can not reproduce this issue. I crafted some food with these bonuses.
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/57239580/8e9e7858-ab7c-4855-929f-b6679c88c396)
Hitting entities doesn't further increase my damage.

**Comment by Daripher** [comment]
I tested this on the latest version and there are no fatal errors from IPL
