### ISSUE TITLE
Bug in the multiplier for breaking mining blocks

### ISSUE THREAD

**Issue by CrawKatt** [Daripher/Passive-Skill-Tree#137]
there is a wrong value entered in the multipliers that breaks the skills related to mining. I would like to collaborate correcting that Bug

**Comment by Daripher** [comment]
Are you sure this bug is present in the latest version of the mod?

**Comment by CrawKatt** [comment]
yes, I was playing with friends on 1.20.1 and we are having problems with mining

**Comment by Daripher** [comment]
I just checked that and it was certainly fixed in the 0.6.3a

**Comment by CrawKatt** [comment]
My friends sent me a videos demonstration of the bug:
### [without skills](https://drive.google.com/file/d/1rOgCehKvCWH0cdqzZoPyho0XCWAeeM2Y/view?usp=sharing)

<details><summary>Skill Tree here</summary>

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/108593932/8d24f5a6-3c40-4f99-876b-93da47118f5d)

</details>

### [with skills](https://drive.google.com/file/d/1MRYVENAX9UhqTeUoaxBV8mAvbAMfOYLH/view?usp=sharing)
<details><summary>Skill Tree here</summary>

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/108593932/677a3fe4-b0dc-467f-ad05-326471e21570)

</details>

For some reason, when raising some of these skills, the speed of mining blocks is slower. There seems to be [a multiplier in the JSON files that is the culprit in the line 6](https://github.com/Daripher/Passive-Skill-Tree/blob/1.20.1/src/generated/resources/data/skilltree/skills/miner_class.json#L6)

**Comment by CrawKatt** [comment]
My friends have just downloaded the latest version. It turns out that the day we downloaded the Mod was the same day that 2 other new versions were released shortly after, leaving us with an older version of the Mod.
