### ISSUE TITLE
Damage bonus visually not represented

### ISSUE THREAD

**Issue by Razbeg** [Daripher/Passive-Skill-Tree#141]
![Stats](https://github.com/Daripher/Passive-Skill-Tree/assets/32352131/435931ac-a62c-48f6-9320-24f6c027505f)
![With shield](https://github.com/Daripher/Passive-Skill-Tree/assets/32352131/156f633e-724a-41e4-802f-05660c96b6f0)
![Without shield](https://github.com/Daripher/Passive-Skill-Tree/assets/32352131/5927d732-d0ae-468b-a6a6-ec9e23213933)

Bonuses to damage is not visually represented in stats as attack speed or others

**Comment by Daripher** [comment]
If you are talking about +65% damage, it is not an attribute bonus, this bonus affects all outgoing player damage.
Attack speed bonus does seem to work according to your screenshots.

**Comment by Razbeg** [comment]
Yes, you're right, but I'm writing about the visual display of the damage bonus as well as for the attack speed, the damage bonus is visible in the window that is added for each point of armor and I thought the percentage damage is not shown and probably not added (I checked with the dummy mod and made sure that it is added)
