### ISSUE TITLE
Gems not registering

### ISSUE THREAD

**Issue by Chorigh** [Daripher/Passive-Skill-Tree#151]
Playing on a multiplayer server and the gems have no texture (purple and black checkered box). Instead of the kind of gem it just says item.skilltree.gem.skilltree.none
![2024-01-11_17 56 04](https://github.com/Daripher/Passive-Skill-Tree/assets/156382410/efae082b-7830-4928-a04f-af1864ab6f1a)

**Comment by maiteko** [comment]
Seeing the same problem. Currently on the 1.19.2 version.

I see compatibility was added for the apotheosis system recently, might have something to do with that.

**Comment by Ke-Hab** [comment]
I think that I have found a solution to this problem. You just need to go into a single player game and log back into the server.

**Comment by Daripher** [comment]
Duplicate of #148
