### ISSUE TITLE
Skill tree stuck (cant add levels and cant add points)

### ISSUE THREAD

**Issue by Mirerew** [Daripher/Passive-Skill-Tree#156]
Hi, iam playing on a Lan Server and i cant buy skillpoints or add skillpoints (i have 2 left). Currently i have 84 skill points . iam playing on version Game: 1.20.1  Mod: 1.20.1-Beta-0.6.6-all. Ive try reseting skill tree, adding levels by command. /kill to reset levels but nothing works.

**Comment by Mirerew** [comment]
No matter how many levels i have it shows the same thing. that iam at 100% from 84 to 85 skill points

**Comment by Aceplante** [comment]
You probably have it configured with a maximum? Maybe it should show "max level" to prevent confusion?

**Comment by ImaSimp-MrYumYum** [comment]
@Aceplante2 Do you know where the config file is?

**Comment by Mirerew** [comment]
yeah i can see it now in config "maximum skill points 85" thats it, thx
