### ISSUE TITLE
Apothesis errors on compat

### ISSUE THREAD

**Issue by itsdinkd** [Daripher/Passive-Skill-Tree#157]
Looks like the setup for the compatibility with apothesis is no longer valid in v1.20.1

(i know the curios errors are because i dont have apothesis curios mod) but im mainly posting this about the other errors like

```
[18Jan2024 11:22:29.297] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing gems file skilltree:citrine_2.
--
428 | [18Jan2024 11:22:29.297] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception:
429 | java.lang.IllegalArgumentException: Invalid GemClass with null or empty types
```

Skill tree: Beta 0.6.6 for 1.20.1 forge
Apothesis: 7.2.2

https://mclo.gs/WoPNnzC

**Comment by Daripher** [comment]
You still need Apothic Curios mod, because my gems use it to be socketed into rings.

**Comment by itsdinkd** [comment]
Sorry I meant to close this. I figured that out shortly after posting this
