### ISSUE TITLE
Gem chance from ores not working [Apotheosis]

### ISSUE THREAD

**Issue by HappyBell92** [Daripher/Passive-Skill-Tree#158]
I started with the skills that give a total of 25% chance to get gems from ores but I have not gotten anything with thousands of ores mined.

When looking at the mod with JEI it says gems are disabled with Apotheosis enabled so I thought it would give Apo gems instead.

**Comment by Daripher** [comment]
What versions of PST and Apotheosis are you using?

**Comment by HappyBell92** [comment]
Ah sorry forgot to include the versions how dumb of me. 

Apotheosis version 7.2.2

Passive Skill Tree version 0.6.6

so both are latest versions

**Comment by Daripher** [comment]
Try installing Apothic Curios

**Comment by HappyBell92** [comment]
Sorry have been busy for the past few days. I installed Apothic Curios and it works now
