### ISSUE TITLE
Performance Issue ticking player

### ISSUE THREAD

**Issue by Water-Moon** [Daripher/Passive-Skill-Tree#161]
It appears that there is some inefficiency in the tick player method, specifically regarding apotheosis compat and getting gem slots. 
Here is what I see in spark's profiler after the server have been running for a few hours:
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/43123946/9345ee4c-cafc-43cb-9574-6fc7ad724d5f)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/43123946/6b76a729-0b91-4f5c-8bb6-85099f976215)

It looks like a result of recursive calls, loops, and serialization, but I'm not sure about it. 

Since performance issue are usually complicated, I apologize ahead if I have mistakenly blamed the wrong mod.

Additional information: we have average of 5 person online during the profiling session, all of them have literally almost maxed out the skill tree (config have been modified to allow 1000 skill points, enough to active every skill in the default tree)

**Comment by Daripher** [comment]
The problem seems to be caused by skill bonuses whose effects are multiplied by the number of gems.

**Comment by Water-Moon** [comment]
Update: weirdly enough, it was a lot better today, but nothing have changed (no mod change, no config change, etc.), and the person online are still the same. I now suspect if there is some external factor, such as connection lag, etc. that might cause certain method calls to hung?

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/43123946/bdca61d5-62bc-4809-85e3-9ef1848b3ca3)

**Comment by Daripher** [comment]
I already made a performance patch for this type of skill bonuses, just in case. I'll include it in the next update.
