### ISSUE TITLE
 crashing with NullPointerException fetching skill bonuses

### ISSUE THREAD

**Issue by grahamfoxrollup** [Daripher/Passive-Skill-Tree#163]
CC: @Daripher 
Passive Skill Tree 0.6.6

Only mod confirmed directly involved from log trace is Passive Skill Tree itself:
```
Caused by: java.lang.NullPointerException
	at daripher.skilltree.skill.bonus.SkillBonusHandler.getPlayerBonuses(SkillBonusHandler.java:561)
```

One player report potentially tied it to the use of Jade skills, but not definitively validated: https://pastebin.com/n4PnzNEP

**Comment by grahamfoxrollup** [comment]
This indicates some code within the SkillBonusHandler in Passive Skill Tree threw the NullPointerException.

No other mods appear directly in the NPE stack trace. So while other mods may have interacted with the player and skill systems, the exception itself occurred within Passive Skill Tree's own code most likely.

**Comment by grahamfoxrollup** [comment]
https://pastebin.com/nsD6wQ7f

**Comment by Daripher** [comment]
Can you check if this was fixed in the latest version of the mod? And send me a new crash log if it wasn't.
