### ISSUE TITLE
Errored gems falling out when digging ore. [1.20.1]

### ISSUE THREAD

**Issue by Jormunrekkr** [Daripher/Passive-Skill-Tree#165]
When playing on a server, errored gems drop out when digging ore.  In a singleplayer game, gems do not drop out at all.  Is there a way to fix this or disable gems from falling out of ore?
<img width="166" alt="image" src="https://github.com/Daripher/Passive-Skill-Tree/assets/159028135/8b8175d9-5ae0-44ea-bcfd-2310c1270d6a">

**Comment by Daripher** [comment]
Are you using the latest versions of PST and Apotheosis?

**Comment by Jormunrekkr** [comment]
PST - 0.6.6
Apotheosis - 7.2.2
At this moment these are the latest versions.

**Comment by Daripher** [comment]
Also make sure you don't have any outdated data packs for PST

**Comment by Jormunrekkr** [comment]
It worked.  Thank you.
