### ISSUE TITLE
Passive Skill Tree mod seems to incompatible with FancyMenu mod

### ISSUE THREAD

**Issue by prrhic** [Daripher/Passive-Skill-Tree#167]
When I reach level 150 in skill tree and buy one more skill point,. My level supposed to increase to the next level 151, but no, it crashes instead. Even though if you set max level to 150 in config, when you click on the experience progress bar - which shows numbers instead of percent, - it will also crashes. When I read the crash report it said the suspected mods were Passive Skill Tree and FancyMenu. I guess they are incompatible?

Here are logs:
crash log: https://gist.github.com/prrhic/639d8cfa616c2aac02d3522f354bc02d
debug log: https://gist.github.com/prrhic/4882d0d5be6eca3d1c936a2bde35d470
latest log: https://gist.github.com/prrhic/3e3905b708998ae1b88cb51f8ea4d500

**Comment by Daripher** [comment]
They might be, looks like this mod changes something in rendering (what a surprise). This might cause my widgets to render when they shouldn't.
You can try disabling this mod to see if it helps, and I'll fix the crash later.

**Comment by prrhic** [comment]
> They might be, looks like this mod changes something in rendering (what a surprise). This might cause my widgets to render when they shouldn't. You can try disabling this mod to see if it helps, and I'll fix the crash later.

Unlucky, the same thing still happening after I have disabled the FancyMenu and it's related mods - Drippy Loading Screen, Konkrete. Still crashing at max level (150) when you click on the experience progress bar. Also If you set higher max level than 150 in config and when you buy another skill point when you're at 150, you'll crash and no longer be able to open the skill tree again cuz it always crash whenever you open it. Here you could check my crash log: https://bytebin.lucko.me/qg5cUId7iV
Oh, and I found a pretty weird bug - When you rejoin the world that you crashed. Your character will be invisible, like it's not being rendered, same thing for all of the entites (Zombie, Villager, etc...) - Yea, all of them are not rendered. And anyone who crashes like that, they will stuck in that bug forever.

**Comment by prrhic** [comment]
Okay so I found the way how to fix it, here the solution. You have to set the level MANUALLY in the config. For example, level 150 requires 87540 XPs. And for the next level - 151, you have to likely create a cost or you can call it a profile for that specific level. Level 151 requires 87541 XPs for example. Oh and you have to count for every single level that you add. Like from 150 to 225, you have to count by yourself. I did my best to explain. Pretty hard to explain since my English is not really good there. Hopefully you understand what I am trying to say lol.
