### ISSUE TITLE
Boot crash with 1.20.1-BETA-0.6.8-all

### ISSUE THREAD

**Issue by SeanChengN** [Daripher/Passive-Skill-Tree#168]
1.20.1-BETA-0.6.7-all version is normal
[2024-02-12-2.log](https://github.com/Daripher/Passive-Skill-Tree/files/14238092/2024-02-12-2.log)

**Comment by CopperGiraffe** [comment]
I second this

**Comment by Busake** [comment]
same, except its 0.6.8 that give the error, im using 0.6.7 and no crash.
