### ISSUE TITLE
Crafted item bonuses don't work with Visual Workbench

### ISSUE THREAD

**Issue by CarpeNatem** [Daripher/Passive-Skill-Tree#169]
updated minecraft mmc4 forge 1.20.1 v25 and found out that passive skill tree all "crafted weapon/armor +%" nodes are not working.
example: allocated "crafted melee weapons: +1 attack damage" and then crafted diamond sword - still 7 damage.
passive skill tree ver: 0.6.7

**Comment by Daripher** [comment]
Try updating the mod and all the dependencies to the latest version. Check if the issue persists.

**Comment by CarpeNatem** [comment]
so the modpack i'm using "medieval MC forge mmc4" has all the dependencies at the latest version. Only the Passive skill tree mod is at 0.6.7. So i updated passive skill tree mod to the latest 0.6.8 and launched a new world and the crafted nodes still don't work.
This mod also has Apotheosis that is at ver 7.2.2 and latest ver is 7.3.0. but unsure if Apotheosis affect crafted nodes specifically.

**Comment by Daripher** [comment]
Fixed in the latest version of Item Production Lib
