### ISSUE TITLE
cannot launch medieval MMC4 forge with IPL 1.0.2 ver

### ISSUE THREAD

**Issue by CarpeNatem** [Daripher/Passive-Skill-Tree#170]
Updated ItemProductionLib mod to 1.0.2 for MC 1.20.1 with modpack medieval MMC4 forge for issue with PassiveSkillTree crafted +% nodes not working properly.
 Currently cannot launch the game anymore. Error log throws out 
"[Render thread/ERROR] Caught exception during event RegisterEvent dispatch for modid visualworkbench"

"Suppressed: net.minecraftforge.fml.ModLoadingException: Visual Workbench (visualworkbench) encountered an error during the common_setup event phase"

![crash](https://github.com/Daripher/Passive-Skill-Tree/assets/159814519/db218ec0-9a95-4029-af2d-5ef82fd020ad)

**Comment by CarpeNatem** [comment]
we're just gonna try to disable VisualWorkbench mod and move on with the latest version of IPL.

**Comment by Daripher** [comment]
> we're just gonna try to disable VisualWorkbench mod and move on with the latest version of IPL.

I'll fix this issue today, don't worry
