### ISSUE TITLE
Crash with containers from other mods

### ISSUE THREAD

**Issue by PydingAbsorber** [Daripher/Passive-Skill-Tree#174]
[crash-2024-02-19_22.40.59-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/14336872/crash-2024-02-19_22.40.59-client.txt)

**Comment by codec-d** [comment]
I am also getting this.
It looks like there was a chain of exceptions occurring, originating from a NullPointerException in the Passive Skill Tree checking code when trying to access the crafting user from the transient crafting container. The key parts of the trace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "daripher.itemproduction.block.entity.Interactive.getUser()" because "this.f_286998_" is null
	at net.minecraft.world.inventory.TransientCraftingContainer.getUser(TransientCraftingContainer.java:1018)
```
This indicates that the f_286998_ field on TransientCraftingContainer was null when Passive Skill Tree tried to access it to get the crafting user.
Further up the stack, it was cascading errors from there through FastSuite and Rats as well, eventually crashing the server tick loop.
