### ISSUE TITLE
Gamecrash when going above set limit - Creative mode

### ISSUE THREAD

**Issue by GamingHQ** [Daripher/Passive-Skill-Tree#176]
Good afternoon. 

I recently discovered a bug in one of the modpacks I use. As it's related to the passive skill tree, I thought letting you know about this as well. Before going into details of this problem, i would like to apologize if this bug has already been flagged and/or patched. If this is the case, you can see this post as not sent. This mod is used in a modpack, so i'm unsure if there would be any custom edits from the modpack creator or not.

**What's happening?**

If you would be going above the maximum set amount of skill points by providing me with xx amount of scrolls to gain a point, the game will crash upon opening the panel but also occurs when consuming a scroll. 

**Reproduce steps**

1. Startup a single-player session
2. Go into cheatos and nacho mode and provide free cheese to yourself.
3. Once at max, you notice that you won't hear a sound. The game will crash with an error code ( Error: 150 ), that a line is too long or something.
4. If you log back in and press a button to open up the specific panel, the game will also crash with the same error. 

**Possible workaround?** 

Yes, resetting your skill tree with the forgot scroll will work.

**Solution for this**

- An option to refuse the user to gain an additional point by scroll usage if user has reached its max. I assume this is handled normally trough the usage of points, but i'm unsure if that's also the case when consuming a scroll.

**Comment by Daripher** [comment]
I'll need a crash log to fix this issue

**Comment by GamingHQ** [comment]
Wauw.. Never thought to see a response coming here after my last several attempts to help modpack owners, but getting the sack in progress. 

I'll see if i can get you a log. Will have to reinstall everything though, so it will take some time.

**Comment by Daripher** [comment]
> I'll see if i can get you a log. Will have to reinstall everything though, so it will take some time.

I've found the source of the issue, don't worry, I'll fix it soon

**Comment by GamingHQ** [comment]
ohh did you? Awesome to hear! Almost wanted to start the download here haha.
