### ISSUE TITLE
Server does not start with version 0.5

### ISSUE THREAD

**Issue by AnemoAI** [Daripher/Passive-Skill-Tree#18]
But it runs fine with version 0.4.9e
To be more precise, it constantly restarting. Should we expect a patch? Has the new version been tested on the servers?
Thank you in advance.

**Comment by Daripher** [comment]
I tested the mod yesterday (both server and client side) with this mod pack:
https://legacy.curseforge.com/minecraft/modpacks/testingpack-for-friends
Can you provide your latest.log file after you experience the issue?

**Comment by AnemoAI** [comment]
[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/12263089/latest.log)
![Error](https://github.com/Daripher/Passive-Skill-Tree/assets/132444053/3f04985a-0b9a-4bcb-b69b-4f4570062431)

I also tried the new version. The problem seems to have changed a little.. The server starts, but when I try to log into it, it starts to reboot. It is worth considering that we have more than 180 mods installed including libraries, but everything works well with version 0.4.9е

**Comment by Daripher** [comment]
Can you provide server log when this issue occurs?

**Comment by AnemoAI** [comment]
What kind of log do you need? I'm attaching everything I can find., I'm not too good at this
[latest (1).log](https://github.com/Daripher/Passive-Skill-Tree/files/12263147/latest.1.log)
[debug.log](https://github.com/Daripher/Passive-Skill-Tree/files/12263149/debug.log)
[crash-2023-08-04_17.28.25-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12263151/crash-2023-08-04_17.28.25-server.txt)

**Comment by AnemoAI** [comment]
This happens when I try to go to the server, and even if I just look in the servers. It is shown as "outdated", and when I try to log in, it shows what is in the screenshot above, and the server starts to reboot constantly.

**Comment by Daripher** [comment]
Ok, now I know what is causing the issue, I hope I will be able to fix this soon

**Comment by AnemoAI** [comment]
Thank you very much! Your mod is amazing, I've been waiting for something like this for a long time (I love PoE so much) and I'll wait for the opportunity to continue playing with it~

**Comment by Daripher** [comment]
This has not been fixed yet so you shouldn't close the issue

**Comment by AnemoAI** [comment]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/132444053/ae94cc33-b4e2-4651-9c28-3e96346a7648)
With version 0.5.2

**Comment by AnemoAI** [comment]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/132444053/635a6e99-d594-40bc-b146-68d6e161b293)
with version 0.5.3 still the same :с
