### ISSUE TITLE
Skills that add perks to crafted gear are not compatible with storage mods 

### ISSUE THREAD

**Issue by meistaGG** [Daripher/Passive-Skill-Tree#180]
Skills that add perks to crafted gear are not compatible with storage mods that have a crafting table built into the network, such as:
1. Tom's Simple Storage
2. Simple Storage Network

Tested on v1.19.2-BETA-0.6.9a, as part of Cisco's Fantasy Medieval RPG series of modpacks. 

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/108792182/b60f2075-3499-40a2-b6ce-5e7b42c0da00)

**Comment by Daripher** [comment]
Since these items aren't technically crafted by the player, I can't apply crafted item bonuses there.
