### ISSUE TITLE
Failed to locate any affixes for air{null} with category LootCategory{ring} and rarity LootRarity{uncommon}

### ISSUE THREAD

**Issue by Tokohiko** [Daripher/Passive-Skill-Tree#19]
Hello.
I've been encountering this issue since updating my server to Apotheosis 6.3.0. This issue has also been replicated in singleplayer.

At the same time, I updated Passive Skill Tree mod to BETA-0.5 and Iron's Spells n' Spellbooks v1.19.2-1.2.0.
I am playing on the Medieval Minecraft modpack, so these three mods were updated manually.

Attached is the crash log and latest.log.
[crash-2023-08-04_03.39.14-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12262215/crash-2023-08-04_03.39.14-server.txt)
[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/12262221/latest.log)

**Comment by Daripher** [comment]
I just made a 0.5.1 update; can you test if you have the same issue with it?

**Comment by Tokohiko** [comment]
It seems the issue persists, unless I did something wrong on my end that skewed the results.

[crash-2023-08-04_08.56.53-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12262450/crash-2023-08-04_08.56.53-server.txt)
[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/12262451/latest.log)

**Comment by SiverDX** [comment]
i checked out the 0.5 version and you were adding affixes to air (but i didn't crash)

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/22003703/d3dbf3ab-9811-43b6-acdb-a4ac10dc6d3a)

generally i'm not sure if the implementation is correct, as I understood it you'd need available affixes otherwise you run into issues (like the one above)

but you don't add your own affixes and you also don't add `rings` and `necklaces` to existing ones
(my guess is it only exists for the sockets?)

**Comment by Daripher** [comment]
Yes, it is only for sockets, but I never experienced that issue, and I don't know how to reproduce it.

**Comment by Daripher** [comment]
Well, it shouldn't give sockets to air for sure.

**Comment by Tokohiko** [comment]
The issue happens sporadically for me.

I could be playing the game just fine for 30 minutes, lets say, up until whatever event is triggered that causes the ticking entity error.

**Comment by SiverDX** [comment]
I'm not which mod does it but you should add an ItemStack.EMPTY in addition to the tag check
Here are my tags for `rings`:

```
balancedflight:ascended_flight_ring
enigmaticlegacy:cursed_ring
enigmaticlegacy:desolation_ring
enigmaticlegacy:ender_ring
enigmaticlegacy:golden_ring
enigmaticlegacy:iron_ring
enigmaticlegacy:magnet_ring
enigmaticlegacy:super_magnet_ring
irons_spellbooks:affinity_ring
irons_spellbooks:cast_time_ring
irons_spellbooks:cooldown_ring
irons_spellbooks:emerald_stoneplate_ring
irons_spellbooks:fireward_ring
irons_spellbooks:frostward_ring
irons_spellbooks:mana_ring
irons_spellbooks:poisonward_ring
irons_spellbooks:silver_ring
malum:gilded_ring
malum:ornate_ring
malum:ring_of_alchemical_mastery
malum:ring_of_arcane_prowess
malum:ring_of_curative_talent
malum:ring_of_desperate_voracity
malum:ring_of_esoteric_spoils
malum:ring_of_the_demolitionist
malum:ring_of_the_hoarder
minecraft:air
relics:bastion_ring
relics:chorus_inhibitor
```

see that `minecraft:air` there?

/forge tags minecraft:item get curios:ring

**Comment by Tokohiko** [comment]
Interesingly, curios:necklace also lists minecraft:air.

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/141409315/1089c641-1a20-4b03-8234-66a4985dc58e)

**Comment by Daripher** [comment]
Well, this is my tag
```
{
  "values": [
    "skilltree:assassin_necklace",
    "skilltree:traveler_necklace",
    "skilltree:healer_necklace",
    "skilltree:simple_necklace",
    "skilltree:scholar_necklace",
    "skilltree:arsonist_necklace",
    "skilltree:fisherman_necklace"
  ]
}
```

**Comment by Daripher** [comment]
I have no idea what mod adds air to these tags

**Comment by SiverDX** [comment]
seems to be from mcreator mods
e. g. https://www.curseforge.com/minecraft/mc-mods/undead-unleashed or https://www.curseforge.com/minecraft/mc-mods/iter-rpg

**Comment by Tokohiko** [comment]
Well then.
Going off of that information, I tested manually deleting the ring data from both of those mods.
And now the error given is calling for the necklace loot category.

[crash-2023-08-04_09.57.56-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12262913/crash-2023-08-04_09.57.56-server.txt)

**Comment by Tokohiko** [comment]
I think that fixed it, actually.

I deleted the ring and necklace curios data from both mods you listed; normally, when I would load the world as a test, the game would almost immediately crash and pull those errors.

I was able to open my world, not crash immediately, and kill a few mobs to generate loot without any issue.

**Comment by Daripher** [comment]
I will still make a fix later to make sure no other mods will mess with jewelry like that

**Comment by Tokohiko** [comment]
Sounds good.

I'll restore the data when the patch comes out and then report back here whether or not the issue persists or another issue generates.
