### ISSUE TITLE
I still have armor bar shown when I'm not wearing the  modified armor. (forge 1.20.1)

### ISSUE THREAD

**Issue by rozumenkov** [Daripher/Passive-Skill-Tree#191]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/119857739/f5630275-c09f-4f7e-a275-25a294bb9e50)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/119857739/858f31bd-9cac-4b17-9aa1-f3f12e4cb7a2)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/119857739/c5f03298-3beb-4550-a3c0-dcb17caa8338)

I just have to put modified armor on once and take it off, then I have this visual bug with a permanent armor bar even when I'm not wearing it. Getting new skills with +armor effect doesn't affect this bar while not wearing armor.

**Comment by Daripher** [comment]
Looks like you have +8 to armor from the skill tree, this doesn't affect armor pieces, it affects your character.
I'm not sure what's the issue here.
