### ISSUE TITLE
Been Having some issues with Apotheosis [1.19.2]

### ISSUE THREAD

**Issue by chummybummy** [Daripher/Passive-Skill-Tree#192]
[crash-2024-04-04_15.12.27-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/14877683/crash-2024-04-04_15.12.27-client.txt)

Both of these mods work fine when the other is taken out of the mod pack, Ive also tried it with just these two mods and I've been having the same problem with it crashing as soon as the world is finished generating.

**Comment by cuoconnell** [comment]
I'm not sure if you have already tried this but rolling back apotheosis to version 6.4.1 has allowed Passive skill tree to work at version 0.6.11. Not a solution but a temporary fix to at least get things rolling. You can do this on the curseforge app by going to the mod page selecting versions and choosing to install the corresponding version number. Or you can go to the curseforge website and select files. From there you can navigate to the Apotheosis-1.19.2-6.4.1.jar and download it that way.
