### ISSUE TITLE
Please push 1.20.1 branch modpack version 0.6.11 source code to github

### ISSUE THREAD

**Issue by bsheth711** [Daripher/Passive-Skill-Tree#195]
Hello, I would like to contribute. However, I believe that the 1.20.1 branch is out of date. The source version is 0.6.10 while the curseforge version is 0.6.11. Thank you for all your work and please push so I can contribute :).

**Comment by Daripher** [comment]
Done

**Comment by bsheth711** [comment]
Thank you!
