### ISSUE TITLE
ModernUI compatible

### ISSUE THREAD

**Issue by Dr-WeiAL** [Daripher/Passive-Skill-Tree#21]
I noticed that this mod has a specialized set of fonts for the interface, but the fonts don't support other languages so it looks weird, and when I installed ModernUI it didn't make the ModernUI fonts work, is there any way to make it compatible?

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/47446553/fdf37bdb-7917-48d7-9fe3-53e217d97735)

**Comment by Daripher** [comment]
That does look like the font has changed, am I missing something?

**Comment by Dr-WeiAL** [comment]
ModernUI will modify the fonts, but Passive Skill Tree seems to override the fonts all over again.
