### ISSUE TITLE
Gems combine into one in invintory

### ISSUE THREAD

**Issue by ianwcart** [Daripher/Passive-Skill-Tree#213]
After making a new world gems error once in inventory. please help ma please, thanks!

![2024-05-22_20 43 15](https://github.com/Daripher/Passive-Skill-Tree/assets/170586225/ea6a4d50-883f-40d2-8f8a-95023ea42a7a)
![2024-05-22_20 43 18](https://github.com/Daripher/Passive-Skill-Tree/assets/170586225/4cdc3fb1-bd18-49d4-9d92-396dd4f9f4fb)

**Comment by ianwcart** [comment]
also i tried the last few updated files from passive skill tree.

**Comment by Daripher** [comment]
Looks like an incompatibility with some mod. Something erases all the gem data from the item stack.

**Comment by ianwcart** [comment]
thanks a bunch i immediately new which mod was doing it, its bigger stacks!

**Comment by bbzzooo** [comment]
que mod daba la incompatibilidad ya que tengo el mismo problema

**Comment by bbzzooo** [comment]
> Muchas gracias, inmediatamente supe qué mod lo estaba haciendo, ¡sus pilas son más grandes!

que mod es el que da la incompatibilidad?

**Comment by ianwcart** [comment]
Very good 👍
