### ISSUE TITLE
Cannot open game again after updateing Apotheosis

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Daripher/Passive-Skill-Tree#23]
0.5 version [fixed Apotheosis's compatibility bug](https://github.com/Daripher/Passive-Skill-Tree/issues/13), however, MC cannot be opened again after updateing Apotheosis to 6.3.2 or higher version.
crash report: https://pastebin.com/XgT70YjW

**Comment by Daripher** [comment]
Thanks. I'm aware of it and will release the update soon.
