### ISSUE TITLE
dupe glitch with material save

### ISSUE THREAD

**Issue by Minecatr** [Daripher/Passive-Skill-Tree#25]
if your inventory is full you can shift click the output item even if you cant take it it will still put more materials in the crafting grid this allows you to get stacks over 64 and dupe items
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/82689952/ef4e75ca-e7db-4857-8e4f-13524a5211e5)

**Comment by Minecatr** [comment]
![Untitled video (2)](https://github.com/Daripher/Passive-Skill-Tree/assets/82689952/7127a9d0-d1a6-44cc-a137-50c46e906fb4)

**Comment by Daripher** [comment]
This is fixed in the latest version since the attribute for saving crafting materials has been removed
