### ISSUE TITLE
Grounded projectiles convert to item instead of entering inventory

### ISSUE THREAD

**Issue by JonXL04** [Daripher/Passive-Skill-Tree#27]
I don't know if this has a purpose, but why do grounded projectiles drop to item form instead of directly entering my inventory?
It's slower and has the risk of destroying them when near fire or a cactus.

https://github.com/Daripher/Passive-Skill-Tree/assets/123087973/6b4a847f-fcb9-494e-a3c0-a3a1e763efb5

**Comment by Daripher** [comment]
It is intended, it was implemented for the arrows so they could directly go into an equipped quiver, I'll make sure the item is also instantly picked up so it's not that noticeable
