### ISSUE TITLE
Scaling should not scale the UI

### ISSUE THREAD

**Issue by Dr-WeiAL** [Daripher/Passive-Skill-Tree#29]
This might be a suggestion, I don't think the UI should be scaled along with the zoom, and a zoom bar should be added to the left or right of the UI if possible
Also I noticed that it doesn't really seem to zoom, but just modifies the UI size, so it would be nice to have smooth zooming, similar to EMI's recipe tree or REI's tags

**Comment by Daripher** [comment]
Yeah, I wanted to implement an actual zoom, it just wasn't a high priority, because the mod had game breaking issues
