### ISSUE TITLE
Skill connection textures break with ModernFix

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Daripher/Passive-Skill-Tree#30]
Installing [ModernFix](https://legacy.curseforge.com/minecraft/mc-mods/modernfix) breaks skill connection textures.

Without ModernFix:
![2023-08-21_07 08 48](https://github.com/Daripher/Passive-Skill-Tree/assets/5104603/cd339936-4e6e-4652-b359-accc768c207d)

With ModernFix:
![2023-08-21_07 09 40](https://github.com/Daripher/Passive-Skill-Tree/assets/5104603/f1b75237-29be-4b5a-b909-ac6e8ffaf7a9)

```
[21Aug2023 07:09:37.299] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: skilltree:/textures/screen/skill_connection.png
java.io.FileNotFoundException: skilltree:/textures/screen/skill_connection.png
```
https://github.com/Daripher/Passive-Skill-Tree/blob/5d4cb13b7fbfe8d96455601e11c92bfba303dc07/src/main/java/daripher/skilltree/client/screen/SkillTreeScreen.java#L516
https://github.com/Daripher/Passive-Skill-Tree/blob/5d4cb13b7fbfe8d96455601e11c92bfba303dc07/src/main/java/daripher/skilltree/client/screen/SkillTreeScreen.java#L531

MC 1.20.1, Forge 47.1.44, Passive Skill Tree 0.5.6, ModernFix 5.7.1+mc1.20.1

**Comment by Daripher** [comment]
I feel like you should report this to the ModernFix author

**Comment by YuRaNnNzZZ** [comment]
Removing the slash after namespace in `ResourceLocation`s mentioned above fixes it though.

**Comment by Daripher** [comment]
Oh, right, I see it now. Ok, I'll remove it then, thanks!
