### ISSUE TITLE
Crashes when making armor on the crafting table

### ISSUE THREAD

**Issue by ZerausDG** [Daripher/Passive-Skill-Tree#31]
hi, sorry for my bad english, I use a translator, my game crashes when I try to make an iron chestplate.

I have a problem with the game when I try to make an iron chestplate, but if it is with a non-vanilla crafting table nothing happens.

I don't know if it's a problem with this mod or not.

MC 1.21.1
Forge 47.1.3
Passive Skill Tree 0.5.6
Polymorph 0.49.0
Visual Workbench 8.0.0

[crash-2023-08-21_16.09.30-server.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12402663/crash-2023-08-21_16.09.30-server.txt)

**Comment by ZerausDG** [comment]
apparently it is a problem with Visual Workbench, removing the mod does not happen again, and someone already reported it on his page.

**Comment by Daripher** [comment]
No, it's related to Visual Workbench, but the source of problem is PST.
