### ISSUE TITLE
problem with the keybinds

### ISSUE THREAD

**Issue by ZerausDG** [Daripher/Passive-Skill-Tree#32]
hi, sorry for my bad english, I use a translator, there is a problem with the key to open the skill tree, the default is the letter "O", but there is also the letter "J", but this is not allowed to modify and interferes with other functions, for example to open the map of the JourneyMap mod.

the problem persists even in a clean installation with only those 2 mods.

also, I don't know if it's normal but the leggings do not have a socket when they are created.

![2023-08-22_23 55 37](https://github.com/Daripher/Passive-Skill-Tree/assets/106796155/dc2f1ee4-6662-45d0-a1ed-7fccc87eeabb)

MC 1.20.1
Passive Skill Tree 0.5.7

**Comment by DMasterIO** [comment]
Hi! i have the same error in MC 1.19.2 with PassiveSkillTree-1.19.2-BETA-0.5.7.jar
