### ISSUE TITLE
Mining Speed underwater

### ISSUE THREAD

**Issue by frenzops** [Daripher/Passive-Skill-Tree#37]
if another mod make you able to mine underwater and this mod is on the mining speed reduction is still aplied 

i found this while using the origin mod (merling)

only applied on pickaxe for some reason

Same thing with being in the air

**Comment by muon-rw** [comment]
Are you sure this is a Passive Skill Tree issue? Last I checked, Origins Forge’s modify break speed power doesn’t work at all.
