### ISSUE TITLE
Incompatibility with latest Curios version

### ISSUE THREAD

**Issue by Xplodin** [Daripher/Passive-Skill-Tree#38]
[crash-2023-09-01_23.36.30-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12503088/crash-2023-09-01_23.36.30-client.txt)

**Comment by HockeyZman2000** [comment]
Similar crash here:
[crash-2023-09-02_23.18.26-client.txt](https://github.com/Daripher/Passive-Skill-Tree/files/12505167/crash-2023-09-02_23.18.26-client.txt)

Occurs when trying to load a world or create a new one
