### ISSUE TITLE
New Hunter branch crashing server

### ISSUE THREAD

**Issue by Aulberon** [Daripher/Passive-Skill-Tree#4]
A player with the hunter branch was able to crash the server by hitting a skeleton with an arrow.

**Comment by Daripher** [comment]
Can you provide your latest.log file? I cannot reproduce the crash myself.

**Comment by Aulberon** [comment]
Tested here and it happens when having the Sniper skill
[latest.log](https://github.com/Daripher/Passive-Skill-Tree/files/11884687/latest.log)

**Comment by Daripher** [comment]
Ah, I see. It is already fixed in the dev branch, I'll release the update soon.
