### ISSUE TITLE
Skill selection interaction improvements

### ISSUE THREAD

**Issue by Dr-WeiAL** [Daripher/Passive-Skill-Tree#41]
When selecting a skill and not confirming it yet it is suggested that a function could be added to cancel the selected skill, perhaps right click to cancel the selection or left click again to cancel the selection so that you don't need to cancel and re-select because of selecting the wrong one

**Comment by Daripher** [comment]
If you want to cancel skill selection, you need to hold shift and click the skill. You can also select multiple skills holding shift key.

**Comment by Daripher** [comment]
Oh, I see, you are talking about skill tree, not the editor, my bad. Forget what I said.

**Comment by Dr-WeiAL** [comment]
Uh, I don't even know what an editor is.
