### ISSUE TITLE
Editor Suggestions

### ISSUE THREAD

**Issue by Bloodpoison** [Daripher/Passive-Skill-Tree#42]
1-Creating New Nodes / Deleting Nodes

2-Changing Node Names

3-Moving Nodes

4-Changing the Amount of Attributes a Node has

5-A Dropdown List of Attributes to Simplyfy Changing the Tree

6-Auto Fill when Manually Writing Attributes (similar to Minecrafts auto fill when pressing Tab i assume?)

7-Changing The Node Borders to Pre determined Nodes? Small Big Special Etc

8-Editing Node Size? Could be Very fun and make Custom Trees more Dynamic
 
- Maybe a Save Changes button? up to you rlly im sure either way ppl will mess up With or without it

Small bug with the Zoom but doesnt rlly matter

**Comment by Bloodpoison** [comment]
9-Moving Nodes by Dragging? using coords is very annoying i feel like a Drag Modus would be very good and Coords just for Fine Tuning the Position

**Comment by Daripher** [comment]
Most features will be added in the next update, if you will be missing something open a new issue
