### ISSUE TITLE
Support for other Minecraft Versions?

### ISSUE THREAD

**Issue by TitooTVGeilo** [Daripher/Passive-Skill-Tree#44]
Hi,
I love your mod and the idear of so a nice design skill tree. But I miss it for other Minecraft Versions. My Favourite Versions was the 1.12.2 and okay yes it is for many People a old Version but I love the Version and the many Mods what it give. But in the theme of Skill Tree mods looks your so good and I hope you can only one version make for the 1.12.2 version.

MFG
Mirko (Titoo8899)

**Comment by Daripher** [comment]
1.12.2 will not be supported, it is very outdated. A lot of features used by the mod simply did not exist on 1.12.2.
