### ISSUE TITLE
[1.19.2]: Resets changes to the break speed from other mods

### ISSUE THREAD

**Issue by SiverDX** [Daripher/Passive-Skill-Tree#48]
https://github.com/Daripher/Passive-Skill-Tree/blob/c81e8cfaf0d0f802300d1416a565ab5abd6770a2/src/main/java/daripher/skilltree/attribute/AttributeBonusHandler.java#L1054

Setting the new speed back to the original speed removes changes from other mods with a higher event priority
I recommend changing the logic, using a higher event priority or using `getNewSpeed()`

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/22003703/988ec9d0-b182-4d72-a080-45678cffd242)

**Comment by Daripher** [comment]
Yeah, I think it was already reported, I will fix it soon.
