### ISSUE TITLE
[1.20.1] No texture transparency

### ISSUE THREAD

**Issue by LuqmaanAbrahams** [Daripher/Passive-Skill-Tree#57]
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/107791578/7edf250e-9755-4ae3-a300-01cd7bb37e50)
image  shows the issue and it doesnt go away if i create a new world or restert minecraft

**Comment by Daripher** [comment]
Does it happen when you have only Passive Skill Tree mod installed?

**Comment by LuqmaanAbrahams** [comment]
will test to see

**Comment by LuqmaanAbrahams** [comment]
works fine with just the mod enabled

**Comment by LuqmaanAbrahams** [comment]
ok i managed to fix it somehow

**Comment by LuqmaanAbrahams** [comment]
it came back again

**Comment by Daripher** [comment]
Are you using Optifine?

**Comment by LuqmaanAbrahams** [comment]
No i am no
I am using oculus

**Comment by DonorKrovi** [comment]
You use ImmediatelyFast
https://github.com/RaphiMC/ImmediatelyFast/issues/131
