### ISSUE TITLE
1.19.2 Apotheosis and Passive Skill Tree Damage Interaction

### ISSUE THREAD

**Issue by tydom22** [Daripher/Passive-Skill-Tree#58]
Mod Versions:
Passive Skill Tree: BETA-0.5.10a
Apotheosis: 6.4.0

Interaction:
Equipping any item in a curios slot seems to increase damage dealt to player by any source by a factor of 2.
Equipping an affixed curio item results in any damage becoming an insta-kill (at minimum enough damage to kill through netherite armor).

**Comment by SiverDX** [comment]
~Works fine in my case~
Actually nevermind, I do notice something similar
It doesn't seem to affect all mobs or happen every time?

Might be some other mod interfering?

**Comment by tydom22** [comment]
I have done a bit of testing in a new pack with just Apotheosis and Passive Skill Tree Installed (and dependencies)
Mod Versions:
Passive Skill Tree: BETA-0.5.10a
Apotheosis: 6.4.0
AttributeFix: 17.2.7
Curios API: 5.1.4.1
Max Health Fix: 8.0.2
Patchouli: 77
Placebo: 7.3.3

Minecraft: 1.19.2
Forge: 43.3.2

It seems consistent on my end, but I've only been using a zombie for damage testing. I do know that when I first saw the issue, it was with a twilight forest naga trophy that was affixed and when placed in the head curios slot would result in a consistent one-shot regardless of input attack damage or armor/protection amounts.

**Comment by SiverDX** [comment]
https://github.com/Daripher/Passive-Skill-Tree/blob/1f0e2192568e779bbaa2c8169cf14b3ae9ef870a/src/main/java/daripher/skilltree/compat/apotheosis/ApotheosisCompatibility.java#L192-L204

Instead of passing the amount and reducing it with each affix you're adding the result of the `onHurt` method on-top therefor multiplying the damage by the number of affixes present

Apotheosis method for comparison:

```java
        Apoth.Affixes.MAGICAL.getOptional().ifPresent(afx -> afx.onHurt(e));
        DamageSource src = e.getSource();
        LivingEntity ent = e.getEntity();
        float amount = e.getAmount();
        for (ItemStack s : ent.getAllSlots()) {
            var affixes = AffixHelper.getAffixes(s);
            for (AffixInstance inst : affixes.values()) {
                amount = inst.onHurt(src, ent, amount);
            }
        }
        e.setAmount(amount);
```

**Comment by tydom22** [comment]
Further testing with a much larger mod list seems to indicate that just putting a necklace on, affixed or not, (i.e. a Reflecting Necklace from 'Relics') is enough to see results of the glitch. This may be due to the default socketing associated with these items ("Socketed 1" currently on the Reflecting Necklace) and the socketing counting as affixes)

> https://github.com/Daripher/Passive-Skill-Tree/blob/1f0e2192568e779bbaa2c8169cf14b3ae9ef870a/src/main/java/daripher/skilltree/compat/apotheosis/ApotheosisCompatibility.java#L192-L204
> 
> Instead of passing the amount and reducing it with each affix you're adding the result of the `onHurt` method on-top therefor multiplying the damage by the number of affixes present
> 
> Apotheosis method for comparison:
> 
> ```java
>         Apoth.Affixes.MAGICAL.getOptional().ifPresent(afx -> afx.onHurt(e));
>         DamageSource src = e.getSource();
>         LivingEntity ent = e.getEntity();
>         float amount = e.getAmount();
>         for (ItemStack s : ent.getAllSlots()) {
>             var affixes = AffixHelper.getAffixes(s);
>             for (AffixInstance inst : affixes.values()) {
>                 amount = inst.onHurt(src, ent, amount);
>             }
>         }
>         e.setAmount(amount);
> ```
