### ISSUE TITLE
[1.19.2] Spells & Shields Compatibility

### ISSUE THREAD

**Issue by Maypul** [Daripher/Passive-Skill-Tree#63]
Hello,
I think it would be great to have an optional branch on the skill tree that would work with Mana added by S&S mod, for example mana regeneration speed.

**Comment by Daripher** [comment]
The tree is fully customizable via data packs. There is also an in-game skill tree editor. You can access it with a **/skilltree editor** command

**Comment by DonorKrovi** [comment]
> The tree is fully customizable via data packs. There is also an in-game skill tree editor. You can access it with a **/skilltree editor** command

How to transfer changes to the server?

**Comment by DonorKrovi** [comment]
I can use editing but it is only on the client side

**Comment by Daripher** [comment]
> I can use editing but it is only on the client side

The editor generates all the data files in your game installation folder. In the **/skilltree/editor** folder. You need to put these files into a data pack.

**Comment by DonorKrovi** [comment]
> > I can use editing but it is only on the client side
> 
> The editor generates all the data files in your game installation folder. In the **/skilltree/editor** folder. You need to put these files into a data pack.

I tried to do this but it didn’t work, can you make an example data pack?

**Comment by Daripher** [comment]
You are probably just missing **pack.mcmeta** file, but I don't have any example data packs.
