### ISSUE TITLE
 PassiveSkillTree-1.20.1-BETA-0.5.8 textures bugging out.

### ISSUE THREAD

**Issue by Lucksinia** [Daripher/Passive-Skill-Tree#65]
__Demonstration:__
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/63837173/e29bd9c9-9f1b-4271-ad54-d2cc3a3fae36)

And this is on 1440x2560 display, so that may be a problem too...

**Comment by Daripher** [comment]
Duplicate of #57
