### ISSUE TITLE
[1.20.1] Armor benefits not working properly 

### ISSUE THREAD

**Issue by LazrProductions** [Daripher/Passive-Skill-Tree#69]
as the blacksmith class, Crafted armor (at it's max level) should each apply double armor but instead it only doubles the last equipped peice.

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/102117526/af0b0c1d-72c5-4b10-af6f-8ccfc3dcbaf4)

and all crafted armor buffs only apply from the helmet (because the game recalculates worn armor when hit).

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/102117526/fd8f6faf-d032-4048-b9ad-c875985ac052)

**Comment by Daripher** [comment]
What Minecraft and game version is this?

**Comment by LazrProductions** [comment]
1.20.1

**Comment by LazrProductions** [comment]
and i want to mention, i am using other mods, it may be an issue with one of them

**Comment by Daripher** [comment]
Yeah, I remember fixing this on 1.19.2, I just didn't update the 1.20.1 yet

**Comment by LazrProductions** [comment]
oh nice, that makes me feel a lot better, i thought i'd have to look through each mod we have to find the issue

**Comment by Daripher** [comment]
I'll fix, don't worry

**Comment by LazrProductions** [comment]
thank you
