### ISSUE TITLE
Crafted Armor/equipment Durability and Defence doesn´t aply ?

### ISSUE THREAD

**Issue by Nerimazeth** [Daripher/Passive-Skill-Tree#7]
I have been testing the mod, but the durability of the armors remained the same as the original after crafting them. I even tried to see if the values were applied as unbreakable, but they still decreased by 1 with each punch. I also tested the amount of armor they provide, but in the statistics, it still increases as per the original without applying the passive effects. I have both dependency mods installed in their latest versions.

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/617fb7fe-8f31-452d-b03a-15e20c0be162)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/ac11104c-4db5-4734-89a2-c540977fa9db)

**Comment by Nerimazeth** [comment]
Here is my mod package. To date, I haven't had any issues with this combination:

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/896a786a-bd81-46af-8886-f665cc317ee2)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/ddf9466a-e72e-4cdc-9492-ef76e0629ba7)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/42806fba-effc-4e31-8088-bccfacc57df9)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/c87df1c5-f15c-49d1-bd5e-0cb4d6cf3b8f)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/2f182bfb-db8e-450d-a145-45fd0aaa5042)

**Comment by Daripher** [comment]
What if you use F3+H to see a tooltip of an item that lost some durability?
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/57239580/944a6ffb-ac18-4a33-9870-e753a549f8f1)

**Comment by Nerimazeth** [comment]
I reassigned the skills for those that used the "crafting" passive abilities, and I crafted that stone sword.

Those "Tough" and "Sharp Blade" abilities are from an addon called "Origins: Classes" for "Origins," which provides small modifications to crafted equipment.

I have an idea that I haven't put into action yet. The next time you respond, I will show it to you. I want to test if using the "Tetra" mod can make the passive abilities from the skill tree work or not.

Before Crafting
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/4f341f91-c200-4706-be4f-a60431186be1)

After crafting
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/13a2a3b6-b125-43fa-b916-711038f432b2)

Same with Leggins
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/206b5200-ee5b-4bb8-bf3d-35bb9f1a6f88)

Edit: I forgot to mention the durability loss. That is with 3 sword strikes and receiving 1 hit to the pants.

![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/a68b5fb1-0424-45c4-9260-bbb074029596)
![image](https://github.com/Daripher/Passive-Skill-Tree/assets/138542166/e0376a74-6d44-4405-8761-e73a29350185)
