### ISSUE TITLE
Attribute modification does not show in GUI

### ISSUE THREAD

**Issue by Caltinor** [Daripher/Passive-Skill-Tree#71]
**Observed Behavior:**
When an attribute is modified via command, the GUI does not reflect the actual value of the attribute.  The effect of the attribute in game is accurate and calling `/attribute @s skilltree:example get` does produce the correct values but the GUI (O -> Show Stats) only shows what is added from the unlocked tiles.

**Expected Behavior:**
attribute modification from external sources reflected in GUI.

**Steps to Reproduce:**
1. create a new world
2. run `/attribute @s skilltree:life_regeneration_bonus modifier add 11111111-1111-1111-1111-111111111111 test 4.00 add`
3. run `/attribute @s skilltree:life_regeneration_bonus get` and observe 4.0 value
4. open PST gui and click "show stats"
5. observe no life regen bonus.
6. run `/summon minecraft:experience_orb ~ ~ ~ {Value:10000}`   <= giving XP via /experience command does not let you skill up in PST
7. buy skill points and unlock the 4 life regeneration tiles on the left of the tree.
8. run the attribute get command again and observe a value of 5.0
9. open the PST GUI and view stats.
10. observe only +1 regen bonus.

As an added test, you use the damage command to harm yourself and see the regen returns 5 HP per heal as expected.

**Additional Context:**
This issue came to my attention when a user of my Project MMO mod attempted to use the attribute perk to boost their PST attributes.  This perk adds a modifier to the attribute, just like the command and the user was not seeing the value reflected in the PST GUI.

**Comment by Daripher** [comment]
The stat list on the right side of the skill tree GUI only shows bonuses from the skill tree, not the values of player attributes.
