### ISSUE TITLE
[1.20.1] Issues with the Jeweler Perk

### ISSUE THREAD

**Issue by Zublac** [Daripher/Passive-Skill-Tree#73]
Hello! We have just recently started the Medieval mod 1.20 forge on our server and i decided to go down the jeweler path. I now have the perk but i cannot for the life of me add a second gem to crafted rings.  Now heres the weird part. Before i didnt have the perk the Copper rings i made did not indicate they had a jeweler socket but i could socket them anyways. then after getting the perk i can now see a Socket but im still not able to put a second gem in the socket. i have a strange feeling the intent was to not have any of the crafted rings have sockets to begin with then once you get the Jeweler perk you can then socket them. just wanted to confirm this. now if it was supposed to be that you cans socket 2 gems into rings then its not working as intended. Just wanted to bring this forward to you as no one on the Luna Pixel discord was sure which way it was supposed to go. 

Thanks so much! Fun mod btw!

**Comment by Daripher** [comment]
Are you playing with Apotheosis? If so, this is related to the fact that there is not compatibility with it on 1.20.1 yet.
