### ISSUE TITLE
A swim speed upgrade?

### ISSUE THREAD

**Issue by Aceplante** [Daripher/Passive-Skill-Tree#78]
Perhaps breath time as well?

underwater mining speed?

**Comment by Daripher** [comment]
Do you need these for your mod pack or do you just want this to be on a main tree? I wasn't planning to add any of these bonuses, but I can add ability to add those in the editor.

**Comment by Aceplante** [comment]
I think this would be a good fit for the main mod, but I suppose a way to add more ourselves would be good, no hurry tho

**Comment by Daripher** [comment]
Not sure if breath time can be adjusted, but I'll add underwater condition for skill bonuses in the next update
