### ISSUE TITLE
Game crashes when clicking on Game Rules to set custom Game rules

### ISSUE THREAD

**Issue by ModernGamingWorld** [Daripher/Passive-Skill-Tree#81]
I went to create a new world using your latest 1.19.2 update and it crashed as soon as I clicked on Gamerules. I would like this to be fixed ASAP

https://gist.github.com/ModernGamingWorld/20b0a95228b82138ec339006c0427268

**Comment by Daripher** [comment]
The fix will be uploaded today.

**Comment by ModernGamingWorld** [comment]
Thanks
